fix: Allow getPendingUsers to be called without arguments (#28)
# Description

When calling `getPendingUsers` with no arguments, I got an error.   I've changed it so this works as a request with all-default parameters (the nulls).

This is the only request method that doesn't just forward the arguments directly as a top-level parameters, so I don't think there are other cases like this one.

The error message I saw:
```
stytch/lib/stytchClient.js:106
        starting_after_id: request["starting_after_id"] || null,
                                  ^

TypeError: Cannot read property 'starting_after_id' of undefined
```

# Tests

- [x] New unit tests for this method
- [x] Integration tested the unit test cases against my live Stytch project